// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLs1pgmr2MeZ-0pAsKB8DOAPscC5g66fU',
    appId: '1:631744135202:android:2ed548234d12f2f1d50a7b',
    messagingSenderId: '631744135202',
    projectId: 'fastagram',
    storageBucket: 'fastagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEhO9Lv_ymkaDpMrIkxeUIK31opbx4DPM',
    appId: '1:631744135202:ios:d07027802bb19e0dd50a7b',
    messagingSenderId: '631744135202',
    projectId: 'fastagram',
    storageBucket: 'fastagram.appspot.com',
    iosClientId: '631744135202-fkjcc855cvb14ju4j8tgk56gjs4vn2tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSns',
  );
}
